### ISSUE TITLE
关于中文翻译的一些想法/建议

### ISSUE THREAD

**Issue by dyxang** [wtttb/Publii-UI-Chinese-simplified#2]
实际上在官方仓库提交中文之前我就上传了一个翻译到Github：[Publii-Chinese-localization](https://github.com/dyxang/Publii-Chinese-localization)，当时为了方便后续翻译更新的方便我把文件放到了Crowdin与Github进行同步：[主页](https://zh.crowdin.com/project/publii-chinese-localization/)
所以我的想法是，我们的翻译进行合并（取长补短之类，我还在修繁体中文的翻译），然后维护Crowdin上面的项目。
不知道是否可行？请回复，谢谢！

**Comment by wtttb** [comment]
当然可以，如果你考虑持续跟进的话就更好了。我去跟官方那边提@ 由你 继续接下来的更新！
我最初是因为看到没有中文语言包，而且那段时间正好在使用这个程序。
现在我在尝试用Hugo自己写。

**Comment by wtttb** [comment]
> 实际上在官方仓库提交中文之前我就上传了一个翻译到Github：[Publii-Chinese-localization](https://github.com/dyxang/Publii-Chinese-localization)，当时为了方便后续翻译更新的方便我把文件放到了Crowdin与Github进行同步：[主页](https://zh.crowdin.com/project/publii-chinese-localization/) 所以我的想法是，我们的翻译进行合并（取长补短之类，我还在修繁体中文的翻译），然后维护Crowdin上面的项目。 不知道是否可行？请回复，谢谢！

当然可以，我最初是因为使用Publii程序不方便，尝试自己翻译一个基础版。现在考虑Hugo自己写。后面应该就不会用Publii程序了。你这边要是有兴趣的话我可以 在官方那里提出 移交到你这边 继续更新。

**Comment by dyxang** [comment]
> > 实际上在官方仓库提交中文之前我就上传了一个翻译到Github：[Publii-Chinese-localization](https://github.com/dyxang/Publii-Chinese-localization)，当时为了方便后续翻译更新的方便我把文件放到了Crowdin与Github进行同步：[主页](https://zh.crowdin.com/project/publii-chinese-localization/) 所以我的想法是，我们的翻译进行合并（取长补短之类，我还在修繁体中文的翻译），然后维护Crowdin上面的项目。 不知道是否可行？请回复，谢谢！
> 
> 当然可以，我最初是因为使用Publii程序不方便，尝试自己翻译一个基础版。现在考虑Hugo自己写。后面应该就不会用Publii程序了。你这边要是有兴趣的话我可以 在官方那里提出 移交到你这边 继续更新。

好的，谢谢！
